### ISSUE TITLE
[x/gamm][StableSwap] Implement Scaling Factors to `CreateStableswapPool`

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#1392] opened 2022-05-03 07:48 UTC
With https://github.com/osmosis-labs/osmosis/pull/1354 being added, we now calculate different assets upon their precision points. 
We should be implementing scaling factors to `CreateStableswapPool`, `NewStableswapPool`, along with `ValidateBasic` if necessary.

**Comment by p0mvn** [comment] 2022-06-27 14:34
This is blocked on deciding the future of: https://github.com/osmosis-labs/osmosis/pull/1459

**Comment by AlpinYukseloglu** [comment] 2022-09-26 23:25
Seems like this is a duplicate of #2166 (please reopen if not)

**Closed by AlpinYukseloglu** 2022-09-26 23:25 UTC
Labels: C:x/gamm, Good first issue, T:task ⚙️
