### ISSUE TITLE
[Placeholder] Simulator epic

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1832] opened 2022-06-20 15:02 UTC
## Background

Epic for simulator, TODO to write this up in more detail

## Suggested Design

> Here, you can put concrete steps as to what to do next
> e.g.
> - create test file in...

## Acceptance Criteria

> Goals & criteria for success
> e.g.
> - all existing and new tests should pass

**Comment by p0mvn** [comment] 2022-06-23 03:53
Duplicate of https://github.com/osmosis-labs/osmosis/issues/1851

**Closed by p0mvn** 2022-06-23 03:53 UTC
Labels: T:epic ⛰
