### ISSUE TITLE
[CL Incentives] Remove `freezeDuration` as a parameter and key component for positions

### ISSUE THREAD

**Issue by AlpinYukseloglu** [osmosis-labs/osmosis#4653] opened 2023-03-17 15:10 UTC
## Background

Now that we let LPs close positions prior to their freeze duration elapsing if they choose the forfeit their rewards, the notion of freezing a position upon joining seems to be a vestigial/path dependent parameter that we should be able to just get rid of.

## Suggested Design

- Instead of forcing LPs to forfeit _all_ their incentives if they haven't reached their freeze duration (which is a slightly silly design given the granularity we have with uptime accumulators), only forfeit the ones that the position doesn't qualify for (i.e. `forfeitIncentives = (curBlockTime - joinTime >= curAccumUptime)`
- Remove `freezeDuration` from `createPosition` message, position key, and all related core logic (e.g. no more need for `freezeDuration >= uptime` checks)
- Update/refactor tests (will likely be difficult)

## Acceptance Criteria

- All existing and new tests should pass

**Comment by p0mvn** [comment] 2023-03-24 23:37
Seems like a duplicate of https://github.com/osmosis-labs/osmosis/issues/4651 but leaving open for now

**Comment by p0mvn** [comment] 2023-03-26 05:08
Closing in favor of #4651 to avoid fragmentation

**Closed by p0mvn** 2023-03-26 05:08 UTC
Labels: F: concentrated-liquidity
