### ISSUE TITLE
EpochInfos ABCI query returns incorrect currentEpochStartTime

### ISSUE THREAD

**Issue by Pharaon1993** [osmosis-labs/osmosis#1799] opened 2022-06-12 18:46 UTC
#### System information

Osmosis version: `Osmosis version`
OS & Version: Linux
osmosisd v10.0.0

#### Expected behavior

currentEpochStartTime is set to the time the block is committed to the blockchain.

See: [Mintscan Log of Epoch 355's block](https://www.mintscan.io/osmosis/blocks/4713066)

#### Actual behavior

currentEpochStartTime is set to the expected time of the Epoch. This is not the case for epochs 355-358 due to the blockchain halt.

{'identifier': 'day', 'startTime': '2021-06-18T17:00:00Z', 'duration': '86400s', 'currentEpoch': '358', 'currentEpochStartTime': '2022-06-11T17:16:09.898160996Z', 'epochCountingStarted': True, 'currentEpochStartHeight': '4713069'}
{'identifier': 'day', 'startTime': '2021-06-18T17:00:00Z', 'duration': '86400s', 'currentEpoch': '357', 'currentEpochStartTime': '2022-06-10T17:16:09.898160996Z', 'epochCountingStarted': True, 'currentEpochStartHeight': '4713068'}
{'identifier': 'day', 'startTime': '2021-06-18T17:00:00Z', 'duration': '86400s', 'currentEpoch': '356', 'currentEpochStartTime': '2022-06-09T17:16:09.898160996Z', 'epochCountingStarted': True, 'currentEpochStartHeight': '4713067'}
{'identifier': 'day', 'startTime': '2021-06-18T17:00:00Z', 'duration': '86400s', 'currentEpoch': '355', 'currentEpochStartTime': '2022-06-08T17:16:09.898160996Z', 'epochCountingStarted': True, 'currentEpochStartHeight': '4713066'}

#### Steps to reproduce the behavior

Send ABCI query to RPC endpoint of a node. Have not tried to reproduce the behavior via CLI.

**Comment by ValarDragon** [comment] 2022-06-13 18:14
So how it acts right now is intended behavior, its a separate question of is this intended behavior the correct semantic.

Each of these epochs is representing an interval of time, and the desire is to have the intervals one after another. E.g. some epoch N starts at time T, but block N is at time T-1, and N+1 is at time T+2. We still want the 'tick' for the epoch to be at time T, evne though we execute it at block N+1, at time T+2.

E.g. we wanted the epochs to run one after another.

**Comment by czarcas7ic** [comment] 2022-06-13 22:22
Ah this makes more sense now. Maybe semantically it should be currentEpochCalculatedStartTime.

**Comment by p0mvn** [comment] 2022-07-15 17:59
Looks like this is resolved?

I'm not sure if this is actionable? IMO, the current name is fine as long as it is documented. I can see some information on this here:
https://github.com/osmosis-labs/osmosis/blob/90d6dd132742cd798a2592beff43965fb36eba17/x/epochs/spec/README.md?plain=1#L32-L35

Let's close this please unless we would like to make this more specific in terms of what we want to accomplish

**Closed by p0mvn** 2022-07-15 17:59 UTC
