### ISSUE TITLE
Distribution module holdings mismatch

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#785] opened 2022-01-25 22:48 UTC
When creating a state export using the command `osmosisd export 2> genesis.json`, even if no modifications are made to the exported genesis, when attempting to use the newly created genesis you will run into a account mismatch error for the distribution module account (see below screenshot). Every time a state export is created, regardless the new module account balance, the mismatch on the new export is always 2 uosmo too high. This issue did not exist pre v6 and I only noticed it recently. After manually correcting the distribution module account by subtracting 2 uosmo, I would then run into an error when checking the bank module that the total osmo supply was off by 2 usomo. Only after manually correcting this as well would the new genesis be accepted and the node would begin to start. 

As @ValarDragon pointed out, this might be related to a rounding error, but not enough time has been put in to confirm this.

![Screen Shot 2022-01-24 at 11 59 26 AM](https://user-images.githubusercontent.com/40078083/151060794-db557c73-9602-4f0e-b0e2-e9f6cc15fc7e.png)

**Comment by ValarDragon** [comment] 2022-01-26 02:04
If the issue is indeed a rounding issue, it may have existed on v5, and instead just be that the mainnet state atm makes us run into such a rounding error.

We should look into the underlying logic for import/export genesis on SDK v0.44.0 in Distribution, and see if a rounding error is possible. If so, I think its fine if we logged this, and had the code / equality check be insensitive to a difference of 2uosmo, but we need to learn more about whats going on first.

**Comment by mattverse** [comment] 2022-02-03 10:37
Current status on investigation:
 ```
moduleHoldings = moduleHoldings.Add(data.FeePool.CommunityPool...)
moduleHoldingsInt, _ := moduleHoldings.TruncateDecimal()
...
if !balances.IsEqual(moduleHoldingsInt) {
panic(fmt.Sprintf("distribution module balance does not match the module holdings: %s <-> %s", balances, moduleHoldingsInt))
}
```
Quite clear that this is where the issue arose, but remains unclear which part of calculation on module holdings results in difference from simply truncating decimal. (Also assumably related to CommunityPool calculation which is also handled and stored in the form of sdk.Dec but unable to locate where error is happening)

**Comment by czarcas7ic** [comment] 2022-02-13 15:47
Got some more info on this. The most recent state export I took required me to changed it by 3 now, not 2. It appears this number is slowly increasing over time. Unsure if this helps at all, just thought I would share this finding.

**Comment by czarcas7ic** [comment] 2022-02-15 00:30
And it's back to 2. So we now know it's not continually increasing and just hovering in that vicinity.

**Comment by mattverse** [comment] 2022-02-15 01:02
Do we need to fix this pre-superfluid staking? @ValarDragon

**Comment by ValarDragon** [comment] 2022-02-15 01:48
Its not critical pre-superfluid staking. The main reason to do it before is if it saves us on testnet setup time / shipping it

**Comment by czarcas7ic** [comment] 2022-02-15 02:24
I already automated the temp fix, so no reason to do this before. Just wanted to document my findings here as I set up more and more testnets so we can refer to them later.

**Comment by mattverse** [comment] 2022-02-15 02:43
Oh wow thats amazing / funny. Thx!

**Comment by ValarDragon** [comment] 2022-09-02 07:43
We decided to close this? Do we want to make an issue in the SDK for them to track?

**Closed** 2024-02-19 17:15 UTC
Labels: sdk-core-module, cosmos-sdk, needs-investigation, frog🐸
