### ISSUE TITLE
Update default mempool max gas per tx to reflect current mainnet

### ISSUE THREAD

**Issue by ibjc** [osmosis-labs/osmosis#5440] opened 2023-06-06 16:42 UTC
## Background

The current default mempool max gas per tx value is the old 25M value:

https://github.com/osmosis-labs/osmosis/blob/c6697a5e4b2ccdf216f213a33db7e97b0dd46399/cmd/osmosisd/cmd/root.go#L151

Along with localosmosis instances, this apparently impacts edgenet? So  transactions that exceed the 25M limit fail:

https://github.com/osmosis-labs/osmosis/blob/c6697a5e4b2ccdf216f213a33db7e97b0dd46399/x/tokenfactory/types/params.go#L16

## Suggested Design

Please update to 120M to reflect current mainnet.

## Acceptance Criteria

When spinning up a localosmosis container, $HOME/.osmosisd-local/config/app.toml's "max-gas-wanted-per-tx" should equal "120000000", like below:

```
ubuntu@ip-xxx-xx-xx-xxx:~/.osmosisd-local/config$ cat app.toml | grep "gas"
minimum-gas-prices = "0uosmo"
  arbitrage-min-gas-fee = ".005"
  max-gas-wanted-per-tx = "120000000" #<-- this guy
  min-gas-price-for-high-gas-tx = ".0025"
```

**Comment by p0mvn** [comment] 2023-06-06 19:06
CC: @DongLieu

**Comment by DongLieu** [comment] 2023-06-07 02:38
ok, tkank you

**Comment by ValarDragon** [comment] 2023-06-08 13:35
No this conclusion isn't right

**Comment by ibjc** [comment] 2023-06-08 13:47
Oh I see; I misunderstood the max gas aspect.

Then yea, the problem behavior of the tokenfactory create denom still exists due to the gas cost of 40M violating the 25M per-tx limit.

**Comment by ValarDragon** [comment] 2023-06-08 13:53
Thanks for flagging the problem, great catch!

Definitely concerning this got so far along / denom creation has been bricked on testnet for people

**Comment by stackman27** [comment] 2023-06-08 17:45
added fix in tokenfactory (https://github.com/osmosis-labs/osmosis/pull/5468) 

@ibjc could you please check if the issue is resolved with this PR

**Comment by ibjc** [comment] 2023-06-08 18:36
thanks, looks good to me!

i generated this issue by spinning up a localosmosis container, and then dispatching the tokenfactory's create denom message.

for testing https://github.com/osmosis-labs/osmosis/pull/5468, i just pointed the repo to the sis/tokenfactory-reduce-gas branch, and rebuilt the container.

the readme.md below roughly outlines the steps i took (except i didn't manually update the gas per tx config):

https://github.com/zodiac-protocol/tokenfactorytest/blob/04f2b6188063bb62a2004213606566b687afbbc7/README.md?plain=1#L5-L53

**Closed** 2023-06-09 14:04 UTC
Labels: Help wanted
