### ISSUE TITLE
Audit ExportGenesis for all modules

### ISSUE THREAD

**Issue by hieuvubk** [osmosis-labs/osmosis#3113] opened 2022-10-24 04:47 UTC
## Background

Refer from [3001](https://github.com/osmosis-labs/osmosis/pull/3001#pullrequestreview-1146224816). We are using state exported to check app state does not change after querying.
So we should audit all modules `ExportGenesis` func to make sure the state is exported without any error.

**Comment by ValarDragon** [comment] 2022-10-28 20:00
duplicate of #2940

**Closed by ValarDragon** 2022-10-28 20:00 UTC
