### ISSUE TITLE
Make balancer inverse relation tests pool generic

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1422] opened 2022-05-05 04:57 UTC
Recently, great tests have been added that test certain invariants (in the tests called "inverse relations") that are expected to hold trrue for any pool: https://github.com/osmosis-labs/osmosis/blob/main/x/gamm/pool-models/balancer/amm_test.go#L89-L216

We should make code reuse possible for using the same core logic in stableswap tests. Theres a couple ways this can be done:

I suggest we do the following:
* Make a general function, perhaps in `pool-models/internal/test_helpers` that defines a testcase struct, which takes in a `PoolI` and some input to try the invariant relation on
* Define testcases in amm_test.go (in the case of balancer, adapt the existing tests, to use a single function call to generate the pool)
  * This should not increase the length of testcase definition notably. Ideally its a one or two liner.
* Add the invariant relation tests to stableswap

There are alternative approaches if for some reason this produces extra overheads though.

**Comment by p0mvn** [comment] 2022-05-05 13:35
Thanks for creating this @ValarDragon . It seems that this might be a duplicate of https://github.com/osmosis-labs/osmosis/issues/1371

@xBalbinus FYI

**Comment by xBalbinus** [comment] 2022-05-05 18:22
Yep! Working on this.

**Comment by p0mvn** [comment] 2022-05-09 03:11
Going to close this since it's a duplicate but porting @ValarDragon 's suggestions to #1371

**Closed by p0mvn** 2022-05-09 03:11 UTC
